### ISSUE TITLE
FlashcardProps (unnötiges Mappen)

### ISSUE THREAD

**Issue by jvanf** [frickerg/Web-Engineering-3#25]
Da hast du recht. Tobi hat ja auch gemeint, dass wir die cards bei der Validierung eigentlich gar nicht fetchen müssen. Das ist ein issue, welches wir noch beheben müssten, um einen besseren flow im prozess zu haben

_Originally posted by @frickerg in https://github.com/frickerg/Web-Engineering-2/pull/16#discussion_r1622068879_

**Comment by frickerg** [comment]
kurz prüfen
