### ISSUE TITLE
Clean-Up Types

### ISSUE THREAD

**Issue by jvanf** [frickerg/Web-Engineering-3#27]
Ich fände es besser, wenn wir alle types zentral anbieten, da wir ja aufeinander aufbauen. Wäre etwas fürs cleanup am schluss 😄

_Originally posted by @frickerg in https://github.com/frickerg/Web-Engineering-2/pull/16#discussion_r1622087509_

**Comment by frickerg** [comment]
@frickerg kurz prüfen:
- Naming alle types
- fontent types nur im frontend (shared möglichst weit unten)
- keine interfaces
