### ISSUE TITLE
UseCallback

### ISSUE THREAD

**Issue by jvanf** [frickerg/Web-Engineering-3#43]
Ich weiss, dass das mein Bock ist, aber man sollte hier wirklich versuchen, bei state-changes nicht zu navigieren, wenn das irgendwie geht?

_Originally posted by @frickerg in https://github.com/frickerg/Web-Engineering-2/pull/40#discussion_r1624552022_

**Comment by frickerg** [comment]
Bitte überprüfen @frickerg
