### ISSUE TITLE
Responsive Design: Card Details

### ISSUE THREAD

**Issue by jvanf** [frickerg/Web-Engineering-3#75]
![image](https://github.com/user-attachments/assets/508c599b-a29d-4193-ad86-33a624e5b421)

**Comment by g0tcoffee** [comment]
- Closed by Branch https://github.com/frickerg/Web-Engineering-3/tree/73-responsive-design-app-bar
- Commit: https://github.com/frickerg/Web-Engineering-3/commit/e25fc4fc924aae0a7a131d785b748be71ac85f13

Sorry, forgot to create branch here first / Lesson Learned: Create feature branches in issue view of github web GUI
